labelToAuthor: {
  "bug": [metacpp]
  "cla-already-signed": []
  "cla-not-required": []
  "cla-required": []
  "cla-signed": []
  "design discussion": []
  "duplicate": []
  "enhancement": []
  "help wanted": []
  "invalid": []
  "kitchen": []
  "microsoft/P2": []
  "microsoft/P3": []
  "need review": []
  "not reproduced": []
  "question": []
  "rake": []
  "ready to merge": []
  "review": []
  "size/M": []
  "size/S": []
  "terraform": []
  "testing": []
  "upstream provider": []
  "wontfix": []
}
