---
driver:
  name: "terraform"
  root_module_directory: "test/integration/fixtures"
  parallelism: 1
  variable_files:
    - "test/integration/fixtures/testing.tfvars"

provisioner:
  name: "terraform"

platforms:
  -
    name: "ubuntu"

transport:
  name: "ssh"
  ssh_key: ~/.ssh/id_rsa

verifier:
  name: "terraform"
  groups:
    -
      name: "remote"
      controls:
        - "operating_system"
      hostnames: "test_target_public_dns"
      port: 22
      username: "azureuser"
    -
      name: "local"
      controls:
        - "state_file"

suites:
  - name: "compute"
