location            = "westus2"
ssh_key             = "~/.ssh/id_rsa.pub"
resource_group_name = "terraform-compute"
vm_os_simple_1      = "UbuntuServer"
vm_os_simple_2      = "Debian"
admin_username      = "azureuser"
admin_password      = "P@ssw0rd12345!"
